export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

export const RATING = {
  MIN: 1,
  MAX: 5,
} as const;

export const LIMITS = {
  SLUG_MAX_LENGTH: 200,
  FULL_NAME_MIN_LENGTH: 2,
  FULL_NAME_MAX_LENGTH: 100,
  BIO_MAX_LENGTH: 1000,
  LOCATION_MAX_LENGTH: 100,
  REVIEW_TEXT_MAX_LENGTH: 2000,
  REVIEW_TITLE_MAX_LENGTH: 120,
  REVIEW_BODY_MIN_LENGTH: 10,
  RELATIONSHIP_MAX_LENGTH: 100,
  SERVICE_DESCRIPTION_MAX_LENGTH: 500,
  PASSWORD_MIN_LENGTH: 8,
  PROFILE_PHOTO_MAX_BYTES: 5 * 1024 * 1024,
} as const;

export const DEFAULTS = {
  AVATAR_URL: "/images/default-avatar.svg",
  AVERAGE_RATING: 0,
  TOTAL_REVIEWS: 0,
} as const;

export const REVIEW_REQUEST = {
  TOKEN_EXPIRY_DAYS: 30,
  STATUSES: ["pending", "completed", "expired"] as const,
} as const;

export const ONBOARDING = {
  STORAGE_KEY: "meritt-onboarding-v1",
  TOTAL_STEPS: 8,
} as const;

export {
  BADGE_TIERS,
  BAYESIAN_CONFIDENCE_C,
  FIXED_THRESHOLD_FALLBACK,
  MIN_COHORT_SIZE_FOR_PERCENTILE,
  MIN_REVIEWS_FOR_ELIGIBILITY,
  PERCENTILE_CUTOFFS,
  RECENCY_HALF_LIFE_DAYS,
  STARTER_BADGE,
  TRUST_SCORE_WEIGHTS,
  VERIFIED_MULTIPLIER,
} from "./badges";
